version: '3.8'

services:
  apache:
    build:
      context: ./apis/passerelle 
    ports:
      - "800:800" 
    depends_on:
      - crud_app
      - auth_app
    networks:
      - my_network

  crud_app:
    build:
      context: ./apis/crud  
    ports:
      - "3001:3001"  
    networks:
      - my_network

  auth_app:
    build:
      context: ./apis/auths  
    ports:
      - "3002:3002"  
    networks:
      - my_network

  react_app:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
